### ISSUE TITLE
ブログを投稿したユーザの名前を、ブログ上に表示させること

### ISSUE THREAD

**Issue by i-kazuyuki** [kazauyuki/DIC_thema_lesson#2]
## 概要
ブログを投稿したユーザの名前を、ブログ上に表示させること

## 完了条件
- [ ] ブログに投稿したユーザーの名前が表示される

## 備考

**Comment by norotime** [comment]
@kazauyuki 今、どこまで実装できているかも付記できると理想的ですね！
:D
