### ISSUE TITLE
全員別々のタスクをイシューとして割り振ること

### ISSUE THREAD

**Issue by i-kazuyuki** [kazauyuki/DIC_thema_lesson#3]
全員別々のタスクをイシューとして割り振ること

**Comment by norotime** [comment]
@kazauyuki いいですね！このイシューも確かに必要です！

**Comment by norotime** [comment]
@kazauyuki 担当者をアサインしましょう！
https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/

**Comment by i-kazuyuki** [comment]
イシューの担当者をアサインしました。
